require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'ReactNativeWalletCore' do
  #use_frameworks!
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  #pod 'TrustWalletCore', '2.9.8'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
